# Generated by Django 3.1.2 on 2020-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201026_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
