# Generated by Django 3.1.2 on 2020-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201109_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
