# Generated by Django 3.1.2 on 2020-10-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('description', models.TextField(max_length=550)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('release_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('publisher', models.CharField(blank=True, max_length=254)),
                ('image_url', models.CharField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('special_offer', models.BooleanField(blank=True, null=True)),
                ('offer_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('twitch_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('consoles', models.ManyToManyField(blank=True, to='games.Console')),
                ('genres', models.ManyToManyField(blank=True, to='games.Genre')),
            ],
        ),
    ]
