# Generated by Django 3.1.2 on 2020-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201008_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='twitch_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
